@echo off

set KEIL_ROOT=C:\Keil
set KEIL_ARM_ROOT=%KEIL_ROOT%

set VCAST_KEIL_ARM_INSTALL_DIR=%KEIL_ROOT%\ARM

set RVCT31INC=%KEIL_ARM_ROOT%\RV31\INC
set RVCT31LIB=%KEIL_ARM_ROOT%\RV31\lib

set PATH=%KEIL_ARM_ROOT%\BIN;%KEIL_ROOT%\UV4;%KEIL_ARM_ROOT%\BIN40;%PATH%;

start %VECTORCAST_DIR%\vcastqt.exe