@echo off

set KEIL_ROOT=C:\Keil\513
set KEIL_C166_ROOT=%KEIL_ROOT%\C166
set VCAST_KEIL_INSTALL_DIR=%KEIL_ROOT% 

set VCAST_KEIL_C166_INSTALL_DIR=%KEIL_ROOT%\C166

set C166INCC=%VCAST_KEIL_C166_INSTALL_DIR%\inc
set C166LIB=%VCAST_KEIL_C166_INSTALL_DIR%\lib

set PATH=%KEIL_C166_ROOT%\BIN;%KEIL_ROOT%\UV4;%KEIL_C166_ROOT%\BIN;%PATH%;

start %VECTORCAST_DIR%\vcastqt.exe
