@echo off

set KEIL_ROOT=C:\Keil\513
set KEIL_ARM_ROOT=%KEIL_ROOT%\ARM

set VCAST_KEIL_INSTALL_DIR=%KEIL_ROOT%

set RVCT31INC=%KEIL_ARM_ROOT%\ARMCC\INC
set RVCT31LIB=%KEIL_ARM_ROOT%\ARMCC\lib

set PATH=%KEIL_ARM_ROOT%\ARMCC\BIN;%KEIL_ROOT%\UV4;%PATH%;

start %VECTORCAST_DIR%\vcastqt.exe
