
REM SET VCAST_DEBUG_PREPROCESSING=1
rem set VCAST_STRIP_TRAILING_BACKSLASHES=1

set PATH=C:\PROGRA~1\IARSYS~1\EMBEDD~1.4\common\bin;C:\PROGRA~1\IARSYS~1\EMBEDD~1.4\430\bin;%PATH%

set VCAST_IAR_INSTALL_DIR=C:\PROGRA~1\IARSYS~1\EMBEDD~1.4\430

pause

rem start %VECTORCAST_DIR%\vcastqt -lc
