
REM SET VCAST_DEBUG_PREPROCESSING=1
rem set VCAST_STRIP_TRAILING_BACKSLASHES=1
set IAR_INSTALL_PATH=C:\PROGRA~2\IARSYS~1\EMBEDD~1.0_0
set PLATFORM=rl78

set PATH=%IAR_INSTALL_PATH%\common\bin;%IAR_INSTALL_PATH%\%PLATFORM%\bin;%PATH%

set VCAST_IAR_INSTALL_DIR=%IAR_INSTALL_PATH%\%PLATFORM%

pause

start %VECTORCAST_DIR%\vcastqt -lc
